# Generated by Django 2.2.1 on 2019-06-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190630_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
