# Generated by Django 2.2.1 on 2019-07-02 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190630_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=45, validators=[django.core.validators.MaxLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MaxLengthValidator(25)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
