# Generated by Django 2.2.5 on 2019-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('trade_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_share_number', models.BigIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSEHistory',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('dsex_index', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_trade', models.BigIntegerField(blank=True, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_market_cap', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSEPrediction',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('future_index', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('future_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
            options={
                'unique_together': {('trade_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('opening_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('trade_code', 'date')},
            },
        ),
    ]
