# Generated by Django 2.2.1 on 2019-06-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190627_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
