# Generated by Django 2.2.1 on 2019-07-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_compan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DseHistory',
        ),
        migrations.DeleteModel(
            name='DsePrediction',
        ),
        migrations.RemoveField(
            model_name='sharehistory',
            name='trade_code',
        ),
        migrations.RemoveField(
            model_name='shareprediction',
            name='trade_code',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='ShareHistory',
        ),
        migrations.DeleteModel(
            name='SharePrediction',
        ),
    ]
