# Generated by Django 2.2.1 on 2019-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20190730_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('trade_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_share_number', models.BigIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
