# Generated by Django 2.2.1 on 2019-08-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePrediction',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('future_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('trade_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
    ]
