# Generated by Django 2.2.1 on 2019-08-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shareprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharePrediction',
        ),
    ]
