# Generated by Django 2.2.1 on 2019-08-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shareprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSEHistory',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('dsex_index', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_trade', models.BigIntegerField(blank=True, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_market_cap', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
    ]
