# Generated by Django 2.2.1 on 2019-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_dsehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSEPrediction',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('future_index', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
    ]
