# Generated by Django 2.2.1 on 2019-08-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dseprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareprediction',
            name='trade_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company', unique=True),
        ),
    ]
