# Generated by Django 2.2.1 on 2019-08-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190827_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareprediction',
            name='trade_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
    ]
