# Generated by Django 2.2.1 on 2019-08-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190827_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
                ('trade_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
    ]
