# Generated by Django 2.2.1 on 2019-08-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190827_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareHistory',
        ),
        migrations.DeleteModel(
            name='SharePrediction',
        ),
    ]
