# Generated by Django 2.2.1 on 2019-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190827_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharePrediction',
            fields=[
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('future_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
