# Generated by Django 2.2.1 on 2019-08-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190828_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('opening_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('future_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
